version: "3.9"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.0.0
    container_name: fm-dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    environment:
      - JVM_OPTS=-Xms512m -Xmx512m
